### PR TITLE
Implementing the function get_dependencies in local and tests

### PR DESCRIPTION
**Pull request by fernandascovino**
Implementation of `get_dependencies` with modification on the `requirements.txt` and addition of tests with `test_get_dependencies.py`

#### Made with @odanoburu

### CODE REVIEW

**Comment by fernandascovino** [comment]
CORRECTIONS: The tests are implemented by the function `test_get_dependencies`, on the file `test_local.py`. We've tested only the possible types of the return from `get_dependencies`. 

I updated the commit changing the variables names and leaving some comments on the code. We still need to format the return of `get_dependencies` to show an dictionary of the packages needed and their versions, instead of the dictionary that it's returning

**Comment by AliferSales** [comment]
Issue #8

**Comment by fccoelho** [comment]
@ThiagoTrabach don't forget to review this Pull request

**Comment by ThiagoTrabach** [comment]
Approved as a first release!
get_dependencies's output can look better.

**Comment by fernandascovino** [comment]
Already updated with fccoelho, all tests passed.

**Pull request merged**
